Allow Swift keywords to be used as names.
mozilla/uniffi-rs pull request #1350
Opened 2022-09-23 22:15 UTC by notmandatory

2022-09-30 01:05 UTC, notmandatory commented
PS. thanks for all the amazing work the uniffi-rs team is doing. ❤️

2022-10-02 02:32 UTC, bendk requested changes
This seems right to me, I'll merge it and I think I can merge the `0.19.x` branch back in to main soon, I don't think you need to make a PR for that.  Do you need a new `0.19.x` dot release?

2022-10-02 02:32 UTC, bendk commented on fixtures/keywords/README.md
> +like a high degree of assurance that each language has a keyword used
+1 to making these small improvements as you work on the code.

2022-10-02 02:32 UTC, merged

2022-10-02 21:07 UTC, notmandatory commented
> This seems right to me, I'll merge it and I think I can merge the `0.19.x` branch back in to main soon, I don't think you need to make a PR for that. Do you need a new `0.19.x` dot release?

Thanks for the merge! our `bdk-ffi` project could use a `0.19.x` dot release, but it's not urgent since I was able to get our last Swift release out using my fork.

2022-10-04 16:51 UTC, thunderbiscuit commented
I just opened the PR for the upgrade to `0.20.0` and everything seems to be working out of the box on our side. I think we should be able to just use that for our next release coming up in two weeks, so no need to do a `0.19.7` patch release.

Thanks a bunch!

bitcoindevkit/bdk-ffi#203

2022-10-21 22:29 UTC, notmandatory commented
I was able to successfully get our `bdk-ffi` project working with the uniffi version 0.21.0. I also added some integration tests with you very useful `build_foreign_language_testcases` macro, it was very easy to use and will help us catch problems much sooner. Thanks again for the awesome project and the new release!