Add external callback interface fixture
mozilla/uniffi-rs pull request #1472
Opened 2023-02-09 21:01 UTC by stan-irl

## Background
- I just tried to ingest the changes from https://github.com/mozilla/uniffi-rs/pull/1456 but my callback interface still failed. It looks like a fairly minor issue.
- I made this PR this minimal reproduction. Maybe you can merge it as an extra test

2023-02-09 21:05 UTC, stan-irl commented
@bendk I'm not sure if this is a bug or you dont plan to support this usecase. Feel free to close

2023-02-09 21:43 UTC, stan-irl commented on uniffi_bindgen/src/interface/types/mod.rs
> +            } => FfiType::UInt64,
not super sure about this - I saw that the regular callback interface is a UInt64 so I just did the same thing here

2023-02-09 21:43 UTC, stan-irl commented on uniffi_bindgen/src/scaffolding/mod.rs
> +                format!("<Box<dyn r#{name}> as uniffi::FfiConverter<crate::UniFfiTag>>")
Again - just trying to handle this the same as a regular callback interface

2023-02-09 21:43 UTC, stan-irl commented on uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs
> +::uniffi::ffi_converter_forward!(Box<dyn r#{{ name }}>, ::{{ crate_name|crate_name_rs }}::UniFfiTag, crate::UniFfiTag);
I dont quite understand the difference between this and uniffi_bindgen/src/scaffolding/mod.rs but I've just tried to do the same thing

2023-02-09 22:10 UTC, stan-irl commented
I'm not sure how to finish this off. I dont think the `external` bindings for the kotlin/python/swift will work here

2023-02-10 07:01 UTC, mhammond commented
I don't really see a reason to not support this - I'd actually like to deprecate callbacks entirely in favor of better support for traits, but that's not going to happen in the short term and these changes do seem sane. Don't the foreign tests just need the relevant imports added in the same way the other external types are referenced? You might find visibility issues (eg, callbacks being private where external ones need to be public or something) though.

2023-02-13 15:13 UTC, stan-irl commented
It's failing because no handles to lift/lower from other crates are generated for callback interfaces when they are for custom types and externals. I will try and add this this afternoon.

2023-02-14 00:24 UTC, bendk requested changes
These changes look good to me, we just need Python and Swift support.

I pushed a commit to my branch that does that: https://github.com/bendk/uniffi-rs/tree/stan_repro_extern_interface_bug

2023-02-14 14:17 UTC, stan-irl commented
@bendk I pulled your changes and the existing tests passed but I added some new ones that fail. Im getting panics in the generated rust scaffolding:
```
impl Drop for UniFFICallbackHandlerUniffiOneCallbackInterface {
    fn drop(&mut self) {
        let callback = FOREIGN_CALLBACK_UNIFFIONECALLBACKINTERFACE_INTERNALS.get_callback().unwrap();
        let mut rbuf = uniffi::RustBuffer::new();
        unsafe { callback(self.handle, uniffi::IDX_CALLBACK_FREE, Default::default(), &mut rbuf) };
    }
}
```

because `FOREIGN_CALLBACK_UNIFFIONECALLBACKINTERFACE_INTERNALS.get_callback()` is returning `None`.

do you know how I can fix this? we're getting pretty deep into the lib. the changes I pulled from you were way over my head

2023-02-14 17:51 UTC, bendk commented
We are definitely getting deep in the lib, thanks for working this out for me.  And unfortunately, we are kind of running into a wall.

Here's the issue:
 - Callback interfaces require the foreign bindings module to register a handler function with Rust.  Rust calls this function when it wants to invoke a callback.
 - With external types, each bindings module opens its own copy of the Rust dynamic library.
 - Therefore if you want to use an external callback interface, you need to register the handler function with your copy of the dylib.


I tried to fix things with [this commit](https://github.com/bendk/uniffi-rs/commit/2a1a9790802d20f7e535b603d2f7c4f88479c2b1).  But then I ran into the second issue.  On Kotlin, each module also defines foreign library as a JNA class and the registration function expects to input that type.  However, since this prevents us from registering the callback with the library from another module.  It still works on Python, because Python uses duck-typing.  It also works on Swift without needing to re-register, I think because Swift directly links to the library file.

So, I think we could land support for Python and Swift right now, but Kotlin isn't ready.  Maybe there's some way to hack around the type issue I mentioned, but I can't think of one.

The long-term fix is to create some system where we can have a shared module and therefore shared types (#1301).

2023-02-14 18:04 UTC, stan-irl commented
ok I understand. that a bummer but if its not currently possible then I guess theres not much we can do.

I'll continue with my workaround of manually merging UDL for now.

thanks for looking into this. I appreciate that this isn't a use case that you need and you still put a lot of time into it 🙂

2023-02-14 18:04 UTC, stan-irl commented
should i close this PR?

2023-02-14 22:56 UTC, mhammond commented
Sorry it didn't work out, but yeah, we might as well close this - thanks for trying though!

2023-02-14 22:56 UTC, closed without merging

2023-02-15 14:37 UTC, bendk commented
Yeah, seems like closing is the best option for now since you have a workaround.  I really appreciate the work you put in on this one.  I'm happy to look into it, since it helped me understand the corner case better.