Allow use of `uniffi::custom_newtype!` from non-root modules
mozilla/uniffi-rs pull request #1691
Opened 2023-08-08 15:11 UTC by ijc

After moving `NewtypeHandle` in the fixture to a submodule I got:

    error[E0433]: failed to resolve: use of undeclared type `UniffiCustomTypeConverter`
       --> fixtures/ext-types/proc-macro-lib/src/lib.rs:168:5
        |
    168 |     uniffi::custom_newtype!(NewtypeHandle, i64);
        |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type `UniffiCustomTypeConverter`
        |
        = note: this error originates in the macro `uniffi::custom_newtype` (in Nightly builds, run with -Z macro-backtrace for more info)

Giving the full path to the type defined in the scaffolding resolves this.

---
/cc @mhammond as mentioned in https://github.com/mozilla/uniffi-rs/issues/1639#issuecomment-1669784472

Fixes: #1639

2023-08-08 15:59 UTC, bendk requested changes
Looks great overal, I just had one suggestion.

2023-08-08 18:26 UTC, mhammond commented
Hey Ian, I just landed #1680 which I think should avoid the need for this work-around - you can just use `uniffi::custom_type!` on the newtype and don't need to annotate the struct at all - see https://github.com/mozilla/uniffi-rs/blob/main/docs/manual/src/proc_macro/index.md#the-unifficustomtype-derive. Sorry for wasting your time and/or let me know if it still doesn't fit your use-case.

2023-08-09 09:16 UTC, ijc commented
Thanks, I'll have another go once I've updated #1690 and either close or update this (looking at #1680 I expect close...).

>  Sorry for wasting your time and/or let me know if it still doesn't fit your use-case.

I was at a bit of a loose end yesterday and it was a useful learning experience, so no problem at all!

2023-08-09 09:40 UTC, ijc commented
With the updated #1690 I still see problems with `UniffiCustomTypeConverter` not being in scope:

```
error[E0433]: failed to resolve: use of undeclared type `UniffiCustomTypeConverter`
   --> fixtures/ext-types/proc-macro-lib/src/lib.rs:168:5
    |
168 |     uniffi::custom_newtype!(NewtypeHandle, i64);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type `UniffiCustomTypeConverter`
    |
    = note: this error originates in the macro `uniffi::custom_newtype` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `UniffiCustomTypeConverter` in this scope
   --> fixtures/ext-types/proc-macro-lib/src/lib.rs:168:5
    |
168 |     uniffi::custom_newtype!(NewtypeHandle, i64);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
    |
    = note: this error originates in the macro `uniffi::custom_newtype` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this trait
    |
165 |     use crate::UniffiCustomTypeConverter;
    |
```

I think because the macro is called within the inner module scope. I does work if I have the macro at the top level but the struct in a submodule, but I think that's not a useful restriction.

I'll have a look and rebase this.

2023-08-09 14:03 UTC, mhammond approved these changes

2023-08-10 07:11 UTC, ijc commented
@bendk you requested a change (which I've made) but that blocks @mhammond's approval from allowing a merge. Could you have another look please?

2023-08-10 14:01 UTC, bendk approved these changes
> @bendk you requested a change (which I've made) but that blocks @mhammond's approval from allowing a merge. Could you have another look please?

Oops, I didn't realize that.  The new code looks great to me.

2023-08-10 14:36 UTC, merged